### ISSUE TITLE
Feature Request: DNS barclamp - do not touch all nodes, when not required

### ISSUE THREAD

**Issue by tpatzig** [sap-oc/crowbar-core#34]
There are some DNS barclamp attributes, that only require changes on the DNS server nodes, not on the DNS clients, e.g. the forwarders.
When applying the DNS proposal it should determine, if it is enough to only run chef on the DNS servers or if really all nodes need to be touched, which takes a huge amount of time.

**Comment by vuntz** [comment]
That's basically the dns instance of https://github.com/sap-oc/crowbar-core/issues/3 -- we need to provide the general framework for this first.

**Comment by matelakat** [comment]
Closing this, as it is tracked by #3
